<h1 align="center">Computational Methods in Environmental Engineering</h1>
<h2 align="center">Lecture #7</h2>
<h3 align="center">28 Feb 2023</h3>



## Numpy so far



-   Multi-dimensional data structures (*faster than lists!*)
-   Array layout and reshaping
-   Indexing
    -   Standard
    -   Slices
    -   Boolean



In [1]:
import numpy as np

## ☛ Hands-on exercises



### Concatenating arrays



-   `np.concatenate` takes a sequence of arrays and joins them along an input axis
    -   `np.vstack` and `np.hstack` are convenience functions for similar functionality



In [2]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

Concatenate the arrays to a $2 \times 6$ array, two different ways



In [16]:
# np.concatenate((arr1, arr2), axis=1)
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Concatenate the arrays to a $6 \times 2$ array, two different ways



In [21]:
# np.concatenate((arr1, arr2)).reshape((6, 2))
np.vstack((arr1.T, arr2.T)).shape

(6, 2)

### Fast element-wise and math operations



Create two random arrays $x$ and $y$ of size $5 \times 4$ and

1.  Generate a new array $m$ that contains the maximum value of the two arrays, i.e., `m[1, 2]` will be the maximum of `x[1,2]` and `y[1,2]`
2.  Calculate the Euclidean distance between $\sqrt{x^2+y^2}$
3.  Calculate the mean of the Euclidean distance

*Hint*: Look up functions [here](https://numpy.org/doc/stable/reference/routines.statistics.html) and [here](https://numpy.org/doc/stable/reference/routines.math.html)



In [23]:
x = np.random.randint(0, 100, (500, 400))
y = np.random.randint(0, 100, (500, 400))

def loopmax(x, y):
    m = np.zeros(x.shape)
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if x[i, j] > y[i, j]:
                m[i, j] = x[i, j]
            else:
                m[i, j] = y[i, j]
    return m

%timeit loopmax(x, y)

63.3 ms ± 290 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
%timeit np.maximum(x, y)

143 µs ± 969 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### Sorting arrays



Use the functions `np.sort` and `np.argsort` to sort the array below



In [2]:
arr = np.random.randint(0, 100, 6)
arr

array([34, 48, 91, 21, 89, 18])

In [3]:
np.sort(arr)

array([18, 21, 34, 48, 89, 91])

In [4]:
arr[np.argsort(arr)]

array([18, 21, 34, 48, 89, 91])