<h1 align="center">Computational Methods in Environmental Engineering</h1>
<h2 align="center">Lecture #6</h2>
<h3 align="center">23 Feb 2023</h3>



## Numerical Python



<blockquote><b>Numpy</b> is one of the most important foundational packages for numerical computing in Python</blockquote>



-   Efficient multidimensional arrays providing fast arithmetic operations and flexible broadcasting capabilities
-   Mathematical functions for fast operations on entire arrays of data without having to write loops
-   Tools for reading/writing array data to disk and working with memory-mapped files
-   Linear algebra, random number generation, and Fourier transform capabilities
-   A C API for connecting NumPy with libraries written in C, C++, or FORTRAN



## Numpy performance



Let's compare a Numpy array with a list



In [1]:
import numpy as np
arr = np.arange(1000000)
lst = list(range(1000000))

Let's multiple each sequence by 2



In [4]:
%time arr2 = arr * 2

CPU times: user 2.49 ms, sys: 2.78 ms, total: 5.27 ms
Wall time: 2.95 ms


In [3]:
%timeit lst2 = [x * 2 for x in lst]

26.3 ms ± 51.8 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## ☛ Hands-on exercises



Use the commands `array`, `empty`, `zeros`, `ones`, and `full` to create 1- and 2-D arrays.



In [11]:
np.full?

Use the commands `arange` and `linspace` to create the array [0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ]



In [24]:
np.arange(0, 5.).dtype
# np.linspace(0, 5., 11)

dtype('float64')

## ndarray memory layout



In [27]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

What is the internal representation?



In [28]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

That means that operating across columns is faster



In [37]:
x = np.zeros((10000, 2000))
# %timeit x.sum(axis=0)
x.sum(axis=1).shape

(10000,)

In [36]:
%timeit x.sum(axis=1)

18.8 ms ± 56.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## ☛ Hands-on exercises



Create a $12 \times 1$ array and use the `reshape` function to change the shape of the array to $4 \times 3$ and $2 \times 6$.



In [40]:
a = np.arange(12)
a.reshape((2, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

Why do the reshaped values follow that order?



Use the `transpose` and `swapaxes` functions to get the transpose of the following array



In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
# arr.transpose()
arr.swapaxes(0, 1)
arr.swapaxes?

## ndarray indexing



-   There are [many ways](https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.indexing.html) to index Numpy ndarrays
-   Basic indexing in Python will return a **view** of the array (increasing efficiency)



In [52]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr[5]

5

In [49]:
arr[5:8]

array([5, 6, 7])

Can we assign to an array slice?



In [50]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [53]:
arr[:] = 11
arr

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

This is an example of **broadcasting**.



### Multidimensional array indexing



<center><img src="https://i.imgur.com/CeLJKEi.png" /></center>



In [54]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr2d[0][2]

3

In [56]:
arr2d[0, 2]

3

Accessing sub-arrays



In [62]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d.shape

(2, 2, 3)

In [64]:
arr3d[0, 1, 1]

5

### Indexing with slices



In [65]:
arr2d[1:3, 0:2]

array([[4, 5],
       [7, 8]])

An alternative way of writing the same



In [66]:
arr2d[1:, :2]

array([[4, 5],
       [7, 8]])

Assignments work as expected



In [67]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

<center><img src="https://i.imgur.com/72qPR1r.png" /></center>



### Boolean indexing



Instead of integer indexing, conditions can be used to index arrays



In [68]:
a = np.array([1, 2, 3, 4])
a[[True,  False, True, False]]

array([1, 3])

Most often we will be using this form of boolean indexing



In [72]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
x[x >= 8].shape
# x.shape

(4,)

What is the shape of *x >= 8*?



Another way of indexing is using the `np.nonzero` function



In [73]:
nz = np.nonzero(x >= 8)
nz

(array([2, 3, 3, 3]), array([2, 0, 1, 2]))

In [74]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [75]:
x[nz]

array([ 8,  9, 10, 11])

We can also use a different array to index our array



In [76]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [77]:
data = np.arange(28).reshape(7, 4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

Suppose each name corresponded to a row in `data`, let's select the rows for Bob:



In [78]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [81]:
data[names == 'Bob']

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

We can combine there to start building powerful expressions



In [82]:
data[names == 'Bob', 2:]

array([[ 2,  3],
       [14, 15]])

To select everything but Bob, we can negate the condition



In [84]:
# data[~(names == 'Bob')]
data[names != 'Bob']

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

Selecting multiple names can be done by combining conditions



In [1]:
mask = (names == 'Bob') | (names == 'Will')
mask

In [1]:
data[mask]

-   The Python keywords `and` and `or` do not work with boolean arrays
-   Use `&` (and) and `|` (or) instead.



In [1]:
data[(data > 2) & (data < 6)]

### Fancy indexing



The term is used to describe indexing using integer arrays



In [1]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

To select a subset of the rows



In [1]:
arr[[4, 3, 0, 6]]

In [1]:
arr[[-3, -5, -7]]